version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - ./logs:/var/log/app
      - ./docker/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  grafana-storage:
